general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/local.toml"
]

[window]
opacity = 0.95
option_as_alt = "OnlyLeft"


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
