#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

def build
  puts 'Build...'
  output = capture './gradlew build 2>&1'
  result = if output.match?(/>Task compile(Test)?Java FAILED/)
             extract_java_errors output
           elsif output.include? 'BUILD SUCCESSFUL'
             'BUILD SUCCESSFUL'
           else
             extract_build_failure output
           end
  puts result
end

def capture(cmd)
  `#{cmd}`
end

def clean
  puts 'Clean...'
  run './gradlew clean > /dev/null 2>&1'
end

def extract_build_failure(output)
  output.scan(/> Task .* FAILED|\* What went wrong:\n(?:.+\n)+/).join
end

def extract_java_errors(output)
  output.scan(/(?:.{0,120}\n)?java:\d+: error.*?(?:\n|$)(?:.{0,120}\n){0,4}/).join "\n"
end

def run(cmd)
  system cmd
end

clean
build
