#!/usr/bin/env ruby
# frozen_string_literal: true

abort 'This script takes no arguments.' unless ARGV.empty?

puts 'Clean…'
`gw clean`

puts 'Build…'
to_capture = ['^> Task', 'Failed to load', 'ApplicationContext', 'SQLSyntaxErrorException', 'Flyway.*Exception',
              'Could not (determine|find|resolve)', 'invalid source release']
to_reject = ['UP-TO-DATE', 'SKIPPED', 'NO-SOURCE', 'failure threshold.*exceeded']
build_output = `gw build 2>&1 | rg -U '#{to_capture.join('|')}' | rg -v '#{to_reject.join('|')}'`

case build_output
when /invalid source release/
  puts build_output[/invalid source release.*/]
  puts 'Set the proper JDK version using SDKMan!'
when /Could not (find|resolve)/
  puts 'Dependency resolution failure:'
  puts build_output.lines.select { |l| l.include? 'Could not' }.join
when /> Task.*compile(Test)?Java FAILED/
  puts 'Compile…'
  puts `gw compileJava compileTestJava --console=plain 2>&1 | rg -A 4 '^/.*java:\\d+: error'`
when /> Task.*compile(IntegrationTest)?Java FAILED/
  puts 'Compile…'
  puts `gw compileIntegrationTestJava --console=plain 2>&1 | rg -A 4 '^/.*java:\\d+: error'`
when /> Task.*compile(Test)?Kotlin FAILED/
  puts 'Compile…'
  puts `gw compileKotlin compileTestKotlin --console=plain 2>&1 | rg -A 4 '^e:.*'`
when /checkstyleMain FAILED/
  puts 'checkstyle…'
  ['service/build/reports/checkstyle/main.html',
   'interfaces/build/reports/checkstyle/main.html'].select { |report| File.file? report }
                                                   .each do |report|
    puts `w3m #{report} | awk '/Violations/,/Back/' | rg -v 'Back to top'`
  end
when /checkstyleTest FAILED/
  puts 'checkstyle…'
  puts `w3m service/build/reports/checkstyle/test.html | awk '/Violations/,/Back/' | rg -v 'Back to top'`
when /spotbugs.*FAILED/
  puts `w3m service/build/reports/spotbugs/*.html | awk '/Code[[:space:]]+Warning/,/Details/' | rg -v 'Details'`
when /Flyway/
  puts build_output
when /(?<!Abstract|ServletWebServer|DefaultUserCode)ApplicationContext\b/
  puts 'Spring context issues:'
  application_context_exceptions = %w[NoSuchBeanDefinitionException SQLSyntaxErrorException
                                      UnsatisfiedDependencyException BeanCreationException BeanInstantiationException]
  puts `fd -u '(Test|IT)\\.html' | xargs -I {} rg '#{application_context_exceptions.join('|')}' {} | uniq`
when /([tT]est|IT).*FAILED/
  puts 'Test failures:'
  puts `fd -u '(Test|IT).*\\.html' | xargs -I {} rg -l 'Failed tests' {} | xargs w3m | awk '/^Failed tests/,/Test/' | rg -v '(Failed tests|Test)'`

  require 'nokogiri'

  Dir.glob('**/*.html')
     .select { |f| File.foreach(f).any? { |l| l.include? 'Failure details' } }
     .map { |f| File.read f }
     .map { |html| Nokogiri::HTML html }
     .map do |doc|
       {
         test_class_name: doc.at_css('a.breadcrumb[href="../index.html"]')&.text,
         test_method_name: doc.at_css('a.breadcrumb[href="index.html"]')&.text,
         test_case_name: doc.at_css('title')&.text&.gsub(/^Test results - /, ''),
         failure_details: doc.at_css('.result-details pre')&.text
       }
     end
     .each do |failure|
       puts [failure[:test_class_name], failure[:test_method_name], failure[:test_case_name]].reject(&:nil?)
                                                                                             .join ' > '
       puts failure[:failure_details]
       puts '---'
     end
when /composeUp FAILED/
  puts '> Task :service:composeUp FAILED'
  puts 'Is Docker running? Restart with calling `kill_docker ; prune_docker ; colima restart`'
else
  puts build_output.lines
                   .reject { |line| line =~ /(Abstract|DefaultUserCode|ServletWebServer)ApplicationContext/ }
                   .join
end
