#!/usr/bin/env ruby
# frozen_string_literal: true

puts 'Clean...'
`gw clean`

puts 'Build...'
build_output = `gw build 2>&1 | rg -U '^> Task|Failed to load ApplicationContext|SQLSyntaxErrorException|Flyway.*Exception' | rg -v 'UP-TO-DATE|SKIPPED|NO-SOURCE'`

case build_output
when /> Task :\w+:compile\w+ FAILED/
  puts 'Compile...'
  puts `gw compileJava compileTestJava --console=plain 2>&1 | rg -A 4 '^/.*java:\\d+: error'`
when /checkstyleMain FAILED/
  puts 'checkstyle...'
  puts `w3m service/build/reports/checkstyle/main.html | awk '/Violations/,/Back/' | rg -v 'Back to top'`
when /checkstyleTest FAILED/
  puts 'checkstyle...'
  puts `w3m service/build/reports/checkstyle/test.html | awk '/Violations/,/Back/' | rg -v 'Back to top'`
when /spotbugs.*FAILED/
  puts `w3m service/build/reports/spotbugs/*.html | awk '/Code[[:space:]]+Warning/,/Details/' | rg -v 'Details'`
when /Flyway/
  puts build_output
when /ApplicationContext/
  puts 'Spring context issues:'
  puts `fd -u '(Test|IT)\\.html' | xargs -I {} rg 'NoSuchBeanDefinitionException' {} | uniq`
when /([tT]est|IT).*FAILED/
  puts 'Test failures:'
  puts `fd -u '(Test|IT)\\.html' | xargs -I {} rg -l 'Failed tests' {} | xargs w3m | awk '/^Failed tests/,/Test/' | rg -v '(Failed tests|Test)'`
when /composeUp FAILED/
  puts '> Task :service:composeUp FAILED'
  puts 'Is Docker running?'
else
  puts build_output
end
