#!/usr/bin/env ruby
# frozen_string_literal: true

message = ARGV[0]
branch_name = `git rev-parse --abbrev-ref HEAD`.strip
prefix = branch_name.gsub(/^(\w+)[-_](\d+).*/, "[\\1-\\2]")
`git commit -m '#{prefix} #{message}'`

status = `gh pr view --json mergeStateStatus -q ".mergeStateStatus"`
if status == 'BEHIND'
  `gh pr update-branch`
  `git fetch --prune`
  `git rebase origin/#{branch_name}`
end
