#!/usr/bin/env bash

export TZ='Europe/Budapest'
input="$1"
if date --version >/dev/null 2>&1; then
    date -d "$input" +%s
else
    if [[ ! "$input" =~ [0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
        input="${input}:00"
    fi
    date -j -f "%Y-%m-%d %H:%M:%S" "$input" +%s
fi
