#!/usr/bin/env ruby
# frozen_string_literal: true

def which(cmd)
  system "command -v #{cmd} >/dev/null 2>&1"
end

def running?(process_name)
  system "pgrep -f '#{process_name}' >/dev/null 2>&1"
end

java_files = `git diff --name-only --diff-filter=ACM`.lines
                                                     .grep(/\.java$/)
                                                     .map(&:chomp)

exit 0 unless java_files.any?

if which 'google-java-format'
  puts java_files.join("\n")
  system 'google-java-format -i --fix-imports-only', *java_files
else
  warn "Warning: google-java-format not found. Install it by running 'brew install google-java-format'."
end

abort 'Skipping IntelliJ formatter: IntelliJ IDEA is currently running.' if running? 'IntelliJ IDEA'

system '/Applications/IntelliJ\\ IDEA.app/Contents/bin/format.sh -s ~/Documents/LatAm_code_style.xml', *java_files
