#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'

author = `git config user.name`.strip

days_in_week = (Date.today.cwday - 1) % 7
previous_monday = Date.today - (days_in_week.zero? ? 7 : days_in_week)

commits = `git log main --author='#{author}' --since='#{previous_monday} 00:00:00' --pretty=format:%s`

puts commits.empty? ? 'No commits found since last Monday.' : commits
