#!/usr/bin/env ruby
# frozen_string_literal: true

def add_exec_bit(path)
  current_mode = File.stat(path)
                     .mode
  new_mode = current_mode | 0o100
  File.chmod new_mode, path unless File.executable? path
end

def extract_version(path)
  File.basename(path)
      .match(/LM-Studio-([0-9.]+)/)&.[](1)
      &.split('.')
      &.map(&:to_i) || []
end

bin_dir = File.expand_path('~/bin')
_, path = Dir.glob(File.join(bin_dir, 'LM-Studio-*'))
             .select { |f| File.file?(f) }
             .each { |path| add_exec_bit(path) }
             .map { |path| [extract_version(path), path] }
             .max_by { |version, _| version }
if path.nil?
  abort "No LMStudio binaries found in #{bin_dir}"
else
  exec path
end
