#!/bin/bash

if command -v ollama &>/dev/null; then
    killall ollama 2>/dev/null
    exec ollama serve
fi

lmstudio_paths=(fd 'LM-Studio-[0-9.]+' "$HOME/bin")
chmod u+x "${lmstudio_paths[@]}"
latest_version=$(printf '%s\n' "${lmstudio_paths[@]}" | sort -V | tail -n 1)
[[ -z "$latest_version" ]] && exit 1
exec "$latest_version"
