#!/usr/bin/env ruby
# frozen_string_literal: true

environment = 'local'
port = `docker ps`.scan(/:(\d+)->3306/)
                  .flatten
                  .first
user = `pass show db/#{environment}_user 2>/dev/null`.strip
password = `pass show db/#{environment}_password 2>/dev/null`.strip
db = `pass show db/#{environment}_db 2>/dev/null`.strip

if File.file? ARGV.first
  puts `mariadb -h 127.0.0.1 -P #{port} -u #{user} -p#{password} --skip-ssl #{db} --table -e \"$(cat #{ARGV.first})"`
else
  puts `mariadb -h 127.0.0.1 -P #{port} -u #{user} -p#{password} --skip-ssl #{db} --table -e \"#{ARGV.first}\"`
end
