- name: Ensure essential repositories are added
  hosts: localhost
  become: true
  gather_facts: true

  vars:
      repositories:
          - name: editors
            baseurl: "https://download.opensuse.org/repositories/editors/"
          - name: utilities
            baseurl: "https://download.opensuse.org/repositories/utilities/"
          - name: mozilla
            baseurl: "https://download.opensuse.org/repositories/mozilla/"
          - name: filesharing
            baseurl: "https://download.opensuse.org/repositories/filesharing/"
          - name: virtualization
            baseurl: "https://download.opensuse.org/repositories/Virtualization/"
          - name: packman
            baseurl: "https://ftp.gwdg.de/pub/linux/misc/packman/suse/"
            packman: true

  tasks:
      - name: Debug distribution info
        debug:
            msg: "Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"

      - name: Add repositories
        zypper_repository:
            name: "{{ item.name }}"
            repo: "{% set base = item.baseurl %}{% if item.packman is defined %}{% if ansible_distribution_version is version_compare('15.6', '==') %}{{ base }}openSUSE_Leap_15.6{% elif ansible_distribution == 'openSUSE Tumbleweed' %}{{ base }}openSUSE_Tumbleweed{% else %}{{ base }}openSUSE_Leap_15.5{% endif %}{% else %}{% if ansible_distribution_version is version_compare('15.6', '==') %}{{ base }}openSUSE_Leap_15.6/{% elif ansible_distribution == 'openSUSE Tumbleweed' %}{{ base }}openSUSE_Tumbleweed/{% else %}{{ base }}openSUSE_Tumbleweed/{% endif %}{% endif %}"
            state: present
            disable_gpg_check: false
            auto_import_keys: true
            overwrite_multiple: true
        loop: "{{ repositories }}"
        when: ansible_os_family == "Suse"
