- name: Ensure the right packages are installed
  become: yes
  hosts: localhost
  tasks:
      - name: Install basic command line tools
        ansible.builtin.package:
            name:
                - bat
                - dust
                - fd
                - fish
                - fzf
                - git
                - git-delta
                - htop
                - jq
                - lsd
                - mc
                - neovim
                - onefetch
                - password-store
                - powerline-fonts
                - python311-pyte # for thefuck
                - python313-setuptools # for thefuck
                - ripgrep
                - starship
                - symbols-only-nerd-fonts
                - thefuck
                - traceroute
                - zoxide
            state: present
      - name: Install packages to non-work environments
        ansible.builtin.package:
            name:
                - MozillaFirefox
                - MozillaThunderbird
                - encfs
                - evince-plugin-djvudocument
                - graphviz
                - lynx
                - neomutt
                - syncthing
                - vlc
                - w3m
                - youtube-dl
            state: present
        when:
            - ansible_virtualization_role != 'guest'
            - not ('microsoft' in ansible_kernel | lower or 'wsl' in ansible_kernel | lower)
            - ansible_architecture != 'aarch64'
      - name: Remove packages from VMs, WSL, or headless systems
        ansible.builtin.package:
            name:
                - MozillaFirefox
                - MozillaThunderbird
            state: absent
        when:
            - ansible_virtualization_role == 'guest' or
              ('microsoft' in ansible_kernel | lower or 'wsl' in ansible_kernel | lower) or
              (ansible_architecture == 'aarch64')

      - name: Remove packages
        ansible.builtin.package:
            name:
                - catfish
                - galculator
                - gigolo
                - icewm
                - mousepad
                - parole
                - pragha
                - remmina
                - gvfs-backend-samba
                - samba
                - samba-ad-dc-libs
                - samba-client
                - samba-client-libs
                - samba-libs
                - samba-libs-python3
                - simple-scan
                - vim
                - vim-data
                - vim-data-common
                - xfce4-dict
            state: absent
