- name: Ensure the right packages are installed
  become: yes
  hosts: localhost
  tasks:
      - name: Install basic command line tools
        ansible.builtin.package:
            name: "{{ item }}"
            state: present
        loop:
            - bat
            - dust
            - fd
            - fish
            - fzf
            - git
            - git-delta
            - hostname
            - htop
            - jq
            - lsd
            - mc
            - neovim
            - onefetch
            - password-store
            - powerline-fonts
            - ripgrep
            - rsync
            - starship
            - symbols-only-nerd-fonts
            - tar
            - traceroute
            - zoxide
        ignore_errors: true
      - name: Install packages on RPi
        ansible.builtin.package:
            name: "{{ item }}"
            state: present
        loop:
            - neomutt
            - syncthing
            - transmission-common
            - transmission-daemon
            - w3m
        ignore_errors: true
        when: ansible_architecture == 'aarch64'
      - name: Install packages to non-work environments
        ansible.builtin.package:
            name: "{{ item }}"
            state: present
        loop:
                - MozillaFirefox
                - MozillaThunderbird
                - encfs
                - evince-plugin-djvudocument
                - evince-plugin-comicsdocument
                - graphviz
                - lynx
                - neomutt
                - syncthing
                - torbrowser-launcher
                - vlc
                - w3m
                - youtube-dl
        ignore_errors: true
        when:
            - ansible_virtualization_role != 'guest'
            - not ('microsoft' in ansible_kernel | lower or 'wsl' in ansible_kernel | lower)
            - ansible_architecture != 'aarch64'
      - name: Remove packages from VMs, WSL, or headless systems
        ansible.builtin.package:
            name:
                - MozillaFirefox
                - MozillaThunderbird
            state: absent
        when:
            - ansible_virtualization_role == 'guest' or
              ('microsoft' in ansible_kernel | lower or 'wsl' in ansible_kernel | lower) or
              (ansible_architecture == 'aarch64')

      - name: Remove packages
        ansible.builtin.package:
            name:
                - catfish
                - galculator
                - gigolo
                - icewm
                - mousepad
                - parole
                - pragha
                - remmina
                - gvfs-backend-samba
                - samba
                - samba-ad-dc-libs
                - samba-client
                - samba-libs
                - samba-libs-python3
                - simple-scan
                - vim
                - vim-data
                - vim-data-common
                - vim-small
                - xfce4-dict
            state: absent
