- name: Update the system
  become: yes
  hosts: localhost
  tasks:
      - name: Update openSUSE
        command: "zypper {% if ansible_distribution == 'openSUSE Tumbleweed' %}dist-upgrade{% else %}update{% endif %} --no-recommends"
        when: ansible_os_family == "Suse"
      - name: Is restart needed?
        command: "zypper ps -s"
        when: ansible_os_family == "Suse"
        register: restart_check_result

      - name: Show restart check output
        debug:
            var: restart_check_result.stdout
        when: ansible_os_family == "Suse"
