# Zenburn Color Palette
set -g fish_color_normal DCDCCC
set -g fish_color_command DCA3A3
set -g fish_color_quote C3BF9F
set -g fish_color_redirection 93C79F
set -g fish_color_end 93C79F
set -g fish_color_error 80D4AA
set -g fish_color_param DCDCCC
set -g fish_color_comment 7F9F7F
set -g fish_color_match DCDCCC
set -g fish_color_selection 444444
set -g fish_color_search_match DCDCCC
set -g fish_color_operator DCDCCC
set -g fish_color_escape DCDCCC
set -g fish_color_cwd 8ACCCF
set -g fish_color_autosuggestion 5C5C5C
set -g fish_color_user 8ACCCF
set -g fish_color_host 93C79F
